unbind r
bind r source-file ~/.config/tmux/tmux.conf
set -sg terminal-overrides ",*:RGB"

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g mouse on
set -g prefix C-s
set -g status-position top
setw -g mode-keys vi

# switch panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-status "top"

# initialize tpm
run '~/.tmux/plugins/tpm/tpm'
