import = [
    "~/dotfiles/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "tmux"

[env]
TERM = "tmux-256color"

[window]
dynamic_title = true

[window.padding]
x = 3
y = 5

[font]
size = 11

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1
