import = [
  "/home/augustin/dotfiles/.config/alacritty/ayu_dark.toml"
]

[env]
TERM = "tmux-256color"

[window]
dynamic_title = true
dynamic_padding = true
opacity = 1

[window.padding]
x = 0
y = 0

[font]
size = 11

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1
