general.import = [
  "ayu_dark.toml"
]

[env]
TERM = "alacritty"

[window]
dynamic_title = true
dynamic_padding = true
opacity = 1

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 2
y = 8

[font]
size = 13

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1
