general.import = []

[env]
TERM = "alacritty"

[colors.primary]
background = "#0B0E14"
[colors.cursor]
cursor = "#ffffff"

[window]
dynamic_title = true
dynamic_padding = true

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 5
y = 5

[font]
size = 14

[font.normal]
family = "Iosevka Term Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0
