general.import = [
  "/home/augustin/dotfiles/.config/alacritty/ayu_dark.toml"
]

[env]
TERM = "tmux-256color"

[window]
dynamic_title = true
dynamic_padding = true
opacity = 1

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 100000

[window.padding]
x = 2
y = 0

[font]
size = 12

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1
