import = [
    "~/dotfiles/.config/alacritty/nord.toml"
]

[shell]
program = "/usr/bin/zsh"
args = ["-c", "tmux"]

[env]
TERM = "tmux-256color"

[window.padding]
x = 0
y = 0

[font]
# Specify the default font size here
size = 10

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 1
