general.import = []

[env]
TERM = "alacritty"

[window]
dynamic_title = true
dynamic_padding = true

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 10
y = 5

[font]
size = 15

[font.normal]
family = "Iosevka Term Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0
