general.import = []

[colors.primary]
background = '#0a0b10'
foreground = '#ebeef5'

[env]
TERM = "alacritty"

[window]
dynamic_title = true
dynamic_padding = true
opacity = 1

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 0
y = 0

[font]
size = 13

[font.normal]
family = "Iosevka Term Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
