[env]
TERM = "tmux-256color"

[window]
dynamic_title = true
opacity = 1

[window.padding]
x = 5
y = 5

[font]
size = 11

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1
